services:

  task-service:
    build: TaskService/.
    container_name: task-service
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/label_tasks
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
      - zookeeper

  api-service:
    build: ApiService/.
    container_name: api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/label_tasks
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BATCH_SERVICE_URL: http://task-service:8080
    depends_on:
      - postgres
      - kafka
      - zookeeper

  answer-service:
    build: AnswerService
    container_name: answer-service
    ports:
      - "8086:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/label_tasks
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      API_SERVICE_URL: http://api:8080
      TASK_SERVICE_URL: http://task-service:8080
    depends_on:
      - postgres
      - kafka
      - zookeeper

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=label_tasks
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--list", "--bootstrap-server", "kafka:9092" ]
      interval: 10s
      retries: 5
      start_period: 20s
